# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WTKWineNew' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WTKWineNew

  target 'WTKWineNewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WTKWineNewUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_frameworks!
  pod “AFNetworking”
  pod “ReactiveCocoa”
  pod “DZNEmptyDataSet”
  pod “Masonry”
  pod “MJRefresh”
  pod “Reachability”
  pod “RESideMenu”
  pod “SDWebImage”
  pod “SVProgressHUD”
  pod “MJExtension”



end
